server:
  port: 8083
  servlet:
    context-path: /wts-fast
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wts-fast?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wang.wts.entity
